services:
  - type: web
    name: creatify-ai-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_USERNAME
        value: "@neyrolooms"
